# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'colorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(217, 156)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_confirm = QtWidgets.QPushButton(Dialog)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout.addWidget(self.btn_confirm)
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "颜色选择"))
        self.comboBox.setItemText(0, _translate("Dialog", "Pastel1"))
        self.comboBox.setItemText(1, _translate("Dialog", "Pastel2"))
        self.comboBox.setItemText(2, _translate("Dialog", "Accent"))
        self.comboBox.setItemText(3, _translate("Dialog", "Dark2"))
        self.comboBox.setItemText(4, _translate("Dialog", "Set1"))
        self.comboBox.setItemText(5, _translate("Dialog", "Set2"))
        self.comboBox.setItemText(6, _translate("Dialog", "Set3"))
        self.comboBox.setItemText(7, _translate("Dialog", "tab10"))
        self.comboBox.setItemText(8, _translate("Dialog", "tab20"))
        self.comboBox.setItemText(9, _translate("Dialog", "tab20b"))
        self.comboBox.setItemText(10, _translate("Dialog", "tab20c"))
        self.comboBox.setItemText(11, _translate("Dialog", "Qualitative"))
        self.btn_confirm.setText(_translate("Dialog", "确定"))
        self.btn_cancel.setText(_translate("Dialog", "取消"))
